version: "3.8"
services:
  backend:
    build: ./backend
    ports: ["5000:5000"]
    env_file: .env.production
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terreiro_db
    volumes:
      - terreiro_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
volumes:
  terreiro_data:
